In [2]:
import pandas as pd
import csv

In [3]:
data = pd.read_csv('user-export-3201559-2025_01_28_12_12_36.csv')

In [4]:
# Convert the data into a DataFrame
df = pd.DataFrame(data)
df

                  $distinct_id              $distinct_id.1
0   01HV7F2Z03B3X3SG7MZC30PSJ2  01HV7F2Z03B3X3SG7MZC30PSJ2
1   01JJEZYVY6WBETJ5PKWX2BG81X  01JJEZYVY6WBETJ5PKWX2BG81X
2   01HXE31W3NH2389NKX2Y56X9MS  01HXE31W3NH2389NKX2Y56X9MS
3   01J1FBBBMDZCWXVPCS11J6R118  01J1FBBBMDZCWXVPCS11J6R118
4   01JJG2F0V03FTD330B5G92NSNF  01JJG2F0V03FTD330B5G92NSNF
5   01JGP9EBHRESHMMGHRWX6VK5Z1  01JGP9EBHRESHMMGHRWX6VK5Z1
6   01HZCRJHWPYRGQ501VWGWVY7KX  01HZCRJHWPYRGQ501VWGWVY7KX
7   01JJEZZG70KPB7MFZYXVM4A08S  01JJEZZG70KPB7MFZYXVM4A08S
8   01HW3JC9SHP0NYPGKSFJ7JGCST  01HW3JC9SHP0NYPGKSFJ7JGCST
9   01JJG2ET3RQ598CFWDMN2N2G4V  01JJG2ET3RQ598CFWDMN2N2G4V
10  01HWXE731KZQ8FH60JPJ0GCTHM  01HWXE731KZQ8FH60JPJ0GCTHM
11  01HV7EQE0CYA1ZWRENMNYKACCA  01HV7EQE0CYA1ZWRENMNYKACCA
12  01JC9CQV0Q5N0X512Y5Q4F51FR  01JC9CQV0Q5N0X512Y5Q4F51FR
13  01HWNPFC4SDS76TF61T6SC1V0K  01HWNPFC4SDS76TF61T6SC1V0K
14  01HV7VWSGKAPNZXNHC8QF6NHRT  01HV7VWSGKAPNZXNHC8QF6NHRT
15  01JFA9NV9FXVT7HGJ26XJMYBJS  01JFA9NV9FXVT7HGJ26XJMYBJS
16  01HV7ENYBRENNXEGTMVFGHN2DZ  01HV7ENYBRENNXEGTMVFGHN2DZ
17  01HV7F7SXV5C4TKGQEBYR4Q0B2  01HV7F7SXV5C4TKGQEBYR4Q0B2
18  01HV7EFBYARF800C2XFNMJJZ42  01HV7EFBYARF800C2XFNMJJZ42
19  01JHDFBQJ575KVF36AJH86R4QW  01JHDFBQJ575KVF36AJH86R4QW
20  01JJDGSNXTG40QWJ6F5CXTE5DY  01JJDGSNXTG40QWJ6F5CXTE5DY
21  01JGSX3NQVS1YXDESH5FY4W07P  01JGSX3NQVS1YXDESH5FY4W07P
22  01HV9EKJT3KE7KDC873JN72JRY  01HV9EKJT3KE7KDC873JN72JRY
23  01HV7P2RS9VH7V74BV3FMTYH98  01HV7P2RS9VH7V74BV3FMTYH98
24  01HXJ4CQWP68GBW0694WX0QRTY  01HXJ4CQWP68GBW0694WX0QRTY
25  01JJG2F3YHZH8EVBBFGR607Q42  01JJG2F3YHZH8EVBBFGR607Q42
26  01JF1DVVMSZN28G42DZHJ10GKC  01JF1DVVMSZN28G42DZHJ10GKC
27  01HWX67H14MBTQAJYKQE8GZ720  01HWX67H14MBTQAJYKQE8GZ720
28  01HV7EKXWQ792C35H78Q8TBWXZ  01HV7EKXWQ792C35H78Q8TBWXZ
29  01HVNP3P98BP7WKHQWKEDYW9VK  01HVNP3P98BP7WKHQWKEDYW9VK
30  01HV7TBAM2398RTAPXN6KX9B2B  01HV7TBAM2398RTAPXN6KX9B2B
31  01HVBGSFAV6X0RKWGJQXRC7RD8  01HVBGSFAV6X0RKWGJQXRC7RD8
32  01HVBXQT2PW19DW9BYNNRC6RSN  01HVBXQT2PW19DW9BYNNRC6RSN
33  01JHF0279BQ392DY10F5729ZAK  01JHF0279BQ392DY10F5729ZAK
34  01HV7GY6HDDTQG9EYJ6MCRHTF6  01HV7GY6HDDTQG9EYJ6MCRHTF6
35  01JBHYRS8681GAB7W6J9MWXZR7  01JBHYRS8681GAB7W6J9MWXZR7
36  01HVXEJ1KKHCAJC0542Q7VAN70  01HVXEJ1KKHCAJC0542Q7VAN70
37  01J83BZ7C72G9TEKYB0CN0T6EM  01J83BZ7C72G9TEKYB0CN0T6EM

In [5]:

# Remove duplicates and extract the unique values from one column
df['$distinct_id']

0     01HV7F2Z03B3X3SG7MZC30PSJ2
1     01JJEZYVY6WBETJ5PKWX2BG81X
2     01HXE31W3NH2389NKX2Y56X9MS
3     01J1FBBBMDZCWXVPCS11J6R118
4     01JJG2F0V03FTD330B5G92NSNF
5     01JGP9EBHRESHMMGHRWX6VK5Z1
6     01HZCRJHWPYRGQ501VWGWVY7KX
7     01JJEZZG70KPB7MFZYXVM4A08S
8     01HW3JC9SHP0NYPGKSFJ7JGCST
9     01JJG2ET3RQ598CFWDMN2N2G4V
10    01HWXE731KZQ8FH60JPJ0GCTHM
11    01HV7EQE0CYA1ZWRENMNYKACCA
12    01JC9CQV0Q5N0X512Y5Q4F51FR
13    01HWNPFC4SDS76TF61T6SC1V0K
14    01HV7VWSGKAPNZXNHC8QF6NHRT
15    01JFA9NV9FXVT7HGJ26XJMYBJS
16    01HV7ENYBRENNXEGTMVFGHN2DZ
17    01HV7F7SXV5C4TKGQEBYR4Q0B2
18    01HV7EFBYARF800C2XFNMJJZ42
19    01JHDFBQJ575KVF36AJH86R4QW
20    01JJDGSNXTG40QWJ6F5CXTE5DY
21    01JGSX3NQVS1YXDESH5FY4W07P
22    01HV9EKJT3KE7KDC873JN72JRY
23    01HV7P2RS9VH7V74BV3FMTYH98
24    01HXJ4CQWP68GBW0694WX0QRTY
25    01JJG2F3YHZH8EVBBFGR607Q42
26    01JF1DVVMSZN28G42DZHJ10GKC
27    01HWX67H14MBTQAJYKQE8GZ720
28    01HV7EKXWQ792C35H78Q8TBWXZ
29    01HVNP3P98BP7WKHQWKEDYW9VK
30    01HV7TBAM2398RTAPXN6KX9B2B
31    01HVBGSFAV6X0RKWGJQXRC7RD8
32    01HVBXQT2PW19DW9BYNNRC6RSN
33    01JHF0279BQ392DY10F5729ZAK
34    01HV7GY6HDDTQG9EYJ6MCRHTF6
35    01JBHYRS8681GAB7W6J9MWXZR7
36    01HVXEJ1KKHCAJC0542Q7VAN70
37    01J83BZ7C72G9TEKYB0CN0T6EM
Name: $distinct_id, dtype: object

In [6]:
comma_separated_ids = ", ".join(df['$distinct_id']).replace(" ", "")

data_comma_sep = [comma_separated_ids]
data_comma_sep

['01HV7F2Z03B3X3SG7MZC30PSJ2,01JJEZYVY6WBETJ5PKWX2BG81X,01HXE31W3NH2389NKX2Y56X9MS,01J1FBBBMDZCWXVPCS11J6R118,01JJG2F0V03FTD330B5G92NSNF,01JGP9EBHRESHMMGHRWX6VK5Z1,01HZCRJHWPYRGQ501VWGWVY7KX,01JJEZZG70KPB7MFZYXVM4A08S,01HW3JC9SHP0NYPGKSFJ7JGCST,01JJG2ET3RQ598CFWDMN2N2G4V,01HWXE731KZQ8FH60JPJ0GCTHM,01HV7EQE0CYA1ZWRENMNYKACCA,01JC9CQV0Q5N0X512Y5Q4F51FR,01HWNPFC4SDS76TF61T6SC1V0K,01HV7VWSGKAPNZXNHC8QF6NHRT,01JFA9NV9FXVT7HGJ26XJMYBJS,01HV7ENYBRENNXEGTMVFGHN2DZ,01HV7F7SXV5C4TKGQEBYR4Q0B2,01HV7EFBYARF800C2XFNMJJZ42,01JHDFBQJ575KVF36AJH86R4QW,01JJDGSNXTG40QWJ6F5CXTE5DY,01JGSX3NQVS1YXDESH5FY4W07P,01HV9EKJT3KE7KDC873JN72JRY,01HV7P2RS9VH7V74BV3FMTYH98,01HXJ4CQWP68GBW0694WX0QRTY,01JJG2F3YHZH8EVBBFGR607Q42,01JF1DVVMSZN28G42DZHJ10GKC,01HWX67H14MBTQAJYKQE8GZ720,01HV7EKXWQ792C35H78Q8TBWXZ,01HVNP3P98BP7WKHQWKEDYW9VK,01HV7TBAM2398RTAPXN6KX9B2B,01HVBGSFAV6X0RKWGJQXRC7RD8,01HVBXQT2PW19DW9BYNNRC6RSN,01JHF0279BQ392DY10F5729ZAK,01HV7GY6HDDTQG9EYJ6MCRHTF6,01JBHYRS8681GAB7W6J9MWXZR7,01HVXEJ1KKHCAJC0542Q7VAN70,01J83BZ7C72G9TEKYB0CN0T6EM']

In [7]:
output_file = 'output.csv'

In [8]:
with open(output_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # Writing the comma-separated list as a single row
    writer.writerow(data_comma_sep)

print(f"Data has been written to {output_file}")

Data has been written to output.csv

In [20]:
len(data_comma_sep)

1

In [9]:
farmingReward = pd.read_csv('farmingRewarded.csv')
farmingParticipate = pd.read_csv('FarmingParticipate.csv')
miningParticipate = pd.read_csv('miningParticipate.csv')
miningReward = pd.read_csv('miningRewarded.csv')

In [10]:
farmingReward

                        userId
0   01JHF0279BQ392DY10F5729ZAK
1   01J83BZ7C72G9TEKYB0CN0T6EM
2   01JHEZT7F8N3MQJSK733V3W4CS
3   01HV7EKXWQ792C35H78Q8TBWXZ
4   01JBHYRS8681GAB7W6J9MWXZR7
5   01J83BZ7QH4BDMZ0WN32NDW192
6   01HV9SK9ZPM76W38DEAHGGK0J4
7   01JFA9NV9FXVT7HGJ26XJMYBJS
8   01JFFK5G414VQVHX7JBQE788CV
9   01HV7F2Z03B3X3SG7MZC30PSJ2
10  01HWX1STGFTH8AZDPGY9F2R3AC
11  01HV74Y9CEMS2PHHPT5YN624RC
12  01JFB3SVWM9YEAESRE416P9SKF
13  01HV8A0S2XB9E7RNBBHCFDA5AY
14  01HW3JC9SHP0NYPGKSFJ7JGCST
15  01JGN5MKTHNXZMV71SYBS88TY3
16  01JFNJSS1Z3CJVKDFXCHMPD44P

In [11]:
farmingParticipate

                        userId
0   01JJ73S11CY34DSPG3EENV09MM
1   01HV7F2Z03B3X3SG7MZC30PSJ2
2   01HV7X0JR2X8PJ5Q9CE2YS0ADV
3   01HV8A0S2XB9E7RNBBHCFDA5AY
4   01HV8HNSSKRHPZCN7BGA17A2R4
5   01HW3JC9SHP0NYPGKSFJ7JGCST
6   01HWX1STGFTH8AZDPGY9F2R3AC
7   01HWX67H14MBTQAJYKQE8GZ720
8   01JBHSR2VWVAX0KX0SM76X05BT
9   01JBHYRS8681GAB7W6J9MWXZR7
10  01JFB3SVWM9YEAESRE416P9SKF
11  01JFFK5G414VQVHX7JBQE788CV
12  01JGN5MKTHNXZMV71SYBS88TY3
13  01JHF0279BQ392DY10F5729ZAK
14  01HV9SK9ZPM76W38DEAHGGK0J4
15  01JFA9NV9FXVT7HGJ26XJMYBJS
16  01JFNJSS1Z3CJVKDFXCHMPD44P
17  01HVEZFQ58S6NCSAEEQGXPF9FV
18  01JHYQD15AQPMP5K7YRQ56PT4R
19  01JJCBZ1ZNT3GHF3JNDX1DAHM1
20  01JJCGED4GBJW07QVD17Q28PG8
21  01HWNPFC4SDS76TF61T6SC1V0K
22  01JJCXV41SKQMHX2VMFC0G0AB2
23  01J83BZ7C72G9TEKYB0CN0T6EM
24  01JGP9EBHRESHMMGHRWX6VK5Z1
25  01JHEZT7F8N3MQJSK733V3W4CS
26  01JJAPVXK7007JR71ABPW95TPW
27  01HV7EKXWQ792C35H78Q8TBWXZ
28  01J83BZ7QH4BDMZ0WN32NDW192
29  01JHDFBQJ575KVF36AJH86R4QW
30  01HV7EQE0CYA1ZWRENMNYKACCA
31  01HV74Y9CEMS2PHHPT5YN624RC

In [14]:
participate_not_reward = farmingParticipate[~farmingParticipate['userId'].isin(farmingReward['userId'])]

# Convert to a comma-separated string
comma_separated_users = ",".join(participate_not_reward['userId'])

# Save to a file
with open("users_not_in_reward.csv", "w") as file:
    file.write(comma_separated_users)

print("File saved: users_not_in_reward.csv")

File saved: users_not_in_reward.csv

In [15]:
participate_not_reward_mining = miningParticipate[~miningParticipate['userId'].isin(miningReward['userId'])]
comma_separated_users = ",".join(participate_not_reward_mining['userId'])

with open("users_not_in_reward_mining.csv", "w") as file:
    file.write(comma_separated_users)

print("File saved: users_not_in_reward_mining.csv")

File saved: users_not_in_reward_mining.csv